import type { Project, SiteSettings } from "./types";
export const defaultSettings: SiteSettings = {
  name: "Alif Rizki",
  role: "Android & Unity Developer",
  headline: "Dari baris kode,",
  headlineAccent: "jadi pengalaman.",
  intro:
    "Halo, aku Alif. Aku membangun aplikasi Android yang memudahkan dan dunia game yang ingin terus dijelajahi.",
  aboutTitle: "Rasa ingin tahu.\nBertemu baris kode.",
  aboutText:
    "Aku Alif Rizki, seorang developer yang senang mengubah ide menjadi sesuatu yang bisa disentuh, dimainkan, dan digunakan. Fokusku ada di pengembangan aplikasi Android dan game menggunakan Unity.\n\nBagiku, detail kecil membuat perbedaan besar. Dari interaksi yang terasa natural sampai mekanik game yang membuat penasaran.",
  location: "Indonesia",
  email: "",
  githubUrl: "",
  linkedinUrl: "",
  heroImage: "/images/liquid.webp",
  heroSecondaryImage: "/images/valley.webp",
  contactTitle: "Punya ide menarik?\nMari wujudkan.",
  skills: ["Android", "Kotlin", "Unity", "C#", "Firebase", "Git"],
  liquidEnabled: true,
};
export const sampleProjects: Project[] = [
  {
    id: "sample-1",
    title: "Ruang Fokus",
    category: "android",
    description:
      "Ruang tenang untuk membangun kebiasaan dan menyelesaikan hal yang berarti.",
    image: "",
    tags: ["Kotlin", "Jetpack Compose"],
    year: "2026",
    downloadUrl: "",
    githubUrl: "",
    playUrl: "",
    published: true,
    order: 0,
    sample: true,
  },
  {
    id: "sample-2",
    title: "Beyond the Valley",
    category: "unity",
    description: "Petualangan kecil di dunia yang menyimpan cerita besar.",
    image: "/images/valley.webp",
    tags: ["Unity", "C#", "Adventure"],
    year: "2026",
    downloadUrl: "",
    githubUrl: "",
    playUrl: "",
    published: true,
    order: 1,
    sample: true,
  },
  {
    id: "sample-3",
    title: "Saku",
    category: "android",
    description:
      "Catat pengeluaran, pahami kebiasaan, dan atur langkah berikutnya.",
    image: "",
    tags: ["Kotlin", "Room Database"],
    year: "2026",
    downloadUrl: "",
    githubUrl: "",
    playUrl: "",
    published: true,
    order: 2,
    sample: true,
  },
  {
    id: "sample-4",
    title: "Orbital",
    category: "unity",
    description:
      "Eksperimen arcade tentang gerak, gravitasi, dan satu percobaan lagi.",
    image: "/images/liquid.webp",
    tags: ["Unity", "C#", "Arcade"],
    year: "2026",
    downloadUrl: "",
    githubUrl: "",
    playUrl: "",
    published: true,
    order: 3,
    sample: true,
  },
];
